added ndk install (#36)
* initial change

* ci fix

* command check added

* output check fix

* updated logging

* udate

* export env

* changed ndk home setting

* clean up

* update

* added retry

* PR changes

* PR changes

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -22,7 +22,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
     - change-workdir:
@@ -53,23 +53,25 @@ workflows:
     before_run:
     - go-tests
     after_run:
+    - test_ndk
     - test_old_gradle
     - test_android-sdk21-tools-21.0.1
     - test_android-sdk20
     - test_android-sdk22-subdir
     - test_react_native
 
-  test_react_native:
+  test_ndk:
     envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/ChainReactApp.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/android-ndk-sample-project.git
     - BRANCH: master
-    - GRADLE_BUILD_FILE_PATH: android/build.gradle
-    - GRADLEW_PATH: android/gradlew
+    - GRADLE_BUILD_FILE_PATH: ./build.gradle
+    - GRADLEW_PATH: ./gradlew
+    - ANDROID_NDK_HOME: ""
     steps:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
     - change-workdir:
@@ -96,7 +98,52 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
+            set -ex
+            rm -rf $ANDROID_HOME/ndk-bundle
+    - path::./:
+        title: Step test installing ndk
+    - path::./:
+        title: Step test installed ndk
+
+  test_react_native:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/ChainReactApp.git
+    - BRANCH: master
+    - GRADLE_BUILD_FILE_PATH: android/build.gradle
+    - GRADLEW_PATH: android/gradlew
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            rm -rf ./_tmp
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+            git init
+            git remote add origin "${SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
             set -ex
             yarn
     - path::./:
@@ -112,7 +159,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
     - change-workdir:
@@ -149,7 +196,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
     - change-workdir:
@@ -186,7 +233,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
     - change-workdir:
@@ -223,7 +270,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
     - change-workdir:
@@ -258,7 +305,7 @@ workflows:
         title: Export go files to test
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
 
             no_vendor_paths="$(go list ./... | grep -v vendor)"
@@ -267,7 +314,7 @@ workflows:
         title: Err check
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
 
             errcheck -asserts=true -blank=true $GOLIST_WITHOUT_VENDOR
@@ -275,7 +322,7 @@ workflows:
         title: Go lint
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
 
             while read -r line; do
@@ -291,7 +338,7 @@ workflows:
         title: Go test
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
 
             go test ./...
@@ -302,7 +349,7 @@ workflows:
         title: Install required testing tools
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
 
             # Check for unhandled errors
@@ -333,7 +380,7 @@ workflows:
         title:
         inputs:
         - content: |
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -e
 
             export CI=true
@@ -346,7 +393,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
             stepman audit --step-yml ./step.yml
 
@@ -384,7 +431,7 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
             bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
             bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
