TOOL-317 #comment Added test case for a project with androidx dependencies. Fixed support lib regex.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -61,7 +61,7 @@ workflows:
     - test_android-sdk22-subdir
     - test_react_native
     - test_ndk_install
-
+    - test_support_library
 
   test_ndk:
     envs:
@@ -216,6 +216,48 @@ workflows:
             #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+            git init
+            git remote add origin "${SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+    - path::./:
+        title: Step test
+
+  test_support_library:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/godrei/JetPackTest.git
+    - BRANCH: master
+    - GRADLE_BUILD_FILE_PATH: build.gradle
+    - GRADLEW_PATH: ./gradlew
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            rm -rf ./_tmp
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            sdkmanager --uninstall "extras;android;m2repository"
     - change-workdir:
         title: Switch working dir to test / _tmp dir
         run_if: true
