initial change

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -7,6 +7,7 @@ app:
 
   # define these in your .bitrise.secrets.yml
   - SAMPLE_APP_URL: https://github.com/bitrise-samples/android-sdk21-tools-21.0.1.git
+  - NDK_SAMPLE_APP_URL: https://github.com/bitrise-samples/android-ndk-sample-project.git
   - BRANCH: master
 
 workflows:
@@ -46,6 +47,44 @@ workflows:
             git remote add origin "${SAMPLE_APP_URL}"
             git fetch || exit 1
             [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+    - path::./:
+        title: Step test
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
+        run_if: true
+        inputs:
+        - path: ..
+        - is_create_path: true
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            rm -rf ./_tmp
+            rm -rf $ANDROID_HOME/ndk-bundle
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            if [[ -z "${NDK_SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no NDK_SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+            git init
+            git remote add origin "${NDK_SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+    - path::./:
+        title: Step test
     - path::./:
         title: Step test
 
